### ISSUE TITLE
[BUG] WotLK and TBC quests completed after WotLK prepatch release do not give appearances

### ISSUE THREAD

**Issue by Palmie** [ClassicWoWCommunity/cata-classic-bugs#1416]
#### 1.1. Description
Currently, any TBC or WotLK quests that were completed after WotLK prepatch release don't seem to be giving appearances retroactively.
  #### 1.2. How to Reproduce
           1. On any character that has done TBC or WotLK quests before cataclysm and after TBC, check your appearances tab
           2. Notice that you are missing appearances for quests that you have completed.
  #### 1.3  Source Material
N/A
#### 2.1. Description
Quest completion should retroactively award appearances for all equippable quest rewards.
  #### 2.2 Source Material
N/A.  It is working for other quests and for TBC quests if you completed them before Wrath prepatch.

Example, I have completed the quest The Elusive Ironjaw on my DK and should have the Helm of Lupine Ferocity, but I do not.
![image](https://github.com/JamminL/cata-classic-bugs/assets/15112626/8cb8ced6-f72f-47f1-9be7-8e4d569853fd)

**Comment by Palmie** [comment]
Let me know if there's any more proof or examples you need for approval, or anything I can clarify.

**Comment by Nithvertigo** [comment]
can confirm this issue. i completed virtually every tbc and wotlk quest (loremaster) and only have appearances from quests redone in other characters post cata launch. also able to provide any additional needed details :)

**Comment by Zereges** [comment]
Can also confirm, this is how ATT looks like for Grizzly

![image](https://github.com/JamminL/cata-classic-bugs/assets/7399594/cbd0156b-2693-4bd9-af68-1285ee293697)

**Comment by Zereges** [comment]
Does this require more confirmation or anything else that would help to solve the issue?

**Comment by Nithvertigo** [comment]
Here's some additional context from a ticket I created. Apparently the item is showing as collected to Blizzard, despite not being in my appearance tab on my end in game. The ticket also confirms that if it is not there (which is the case) that this is a bug. 
![Screenshot (2230)](https://github.com/user-attachments/assets/d95ed148-3ef8-43f0-b7dd-88487bdc04f0)
![Screenshot (2229)](https://github.com/user-attachments/assets/e3a83705-cd39-4e57-b2da-0285cb3cfe17)
![Screenshot (2228)](https://github.com/user-attachments/assets/39ffe0a6-c321-4425-9df6-9d9536ba8fc6)
![Screenshot (2227)](https://github.com/user-attachments/assets/97751890-2743-4a95-9255-a5240410f5b7)

**Comment by Artemishowl** [comment]
Ugh, this seems tricky. Thank you all for the reports, a ticket is made and escalated.

**Comment by Artemishowl** [comment]
Update: This will be fixed next patch, which doesn't have a public announcement date yet but it is squashed!

**Comment by maximkad2** [comment]
Current fix that is active on PTR still do not award some appearances, all quests have been completed prior to cata and C_QuestLog.IsQuestFlaggedCompleted returns true for all of them, only checked hunter usable appearances
![image](https://github.com/user-attachments/assets/34fd7d9f-5242-4f85-a5de-590271cbc04e)
![image](https://github.com/user-attachments/assets/7555fcee-82f7-4f0d-afec-93ed31d522f0)
![image](https://github.com/user-attachments/assets/74ba1f39-2d40-4923-8e94-14271d6097d4)

**Comment by ZeChrales** [comment]
It's still not fixed with Molten Front patch 4.4.0.56489. Will it be only in next 4.4.1.x major patch @Artemishowl ?

**Comment by maximkad2** [comment]
Still not fixed on recent ptr

**Comment by maximkad2** [comment]
still broken on live, all quest have been completed prior to cata, are still complete, characters have been logged on after patch, yet rewards still missing
![image](https://github.com/user-attachments/assets/9a6c1ccd-3b0b-4c8a-b192-069746669d76)
![image](https://github.com/user-attachments/assets/64d184c0-c0d7-4622-aada-407d949c0620)
![image](https://github.com/user-attachments/assets/758f32eb-2dd3-403f-947f-d0ad22c6207f)
![image](https://github.com/user-attachments/assets/50c044e1-b37f-42c1-89c6-4e85f738c33f)
![image](https://github.com/user-attachments/assets/a142f103-747a-4242-ba60-ebd26ea3e0ce)
![image](https://github.com/user-attachments/assets/62adc5b9-8620-4e70-b63d-df3f70e20fdf)
![image](https://github.com/user-attachments/assets/940cc750-f3b0-446d-b0b2-c6681b08afb1)
![image](https://github.com/user-attachments/assets/169d5981-0e82-47ec-a8b5-5ebac8766ccb)
![image](https://github.com/user-attachments/assets/2fa60dd0-4db6-40a0-8ecd-369d3df3be9b)

**Comment by ZeChrales** [comment]
Original issue (missing appearances from classic/bc/wotlk quests already finished) is now correctly fixed in 4.4.1.57294, thanks a lot :)

**Comment by Zereges** [comment]
Classic (precata) quests are not fixed. Random example follows. Should we create a new issue for appearences from  quests that were removed in Cata?

![image](https://github.com/user-attachments/assets/40371845-a829-420b-a05e-10c07b921003)

**Comment by ZeChrales** [comment]
> Classic (precata) quests are not fixed. Random example follows. Should we create a new issue for appearences from quests that were removed in Cata?
> 
> ![image](https://private-user-images.githubusercontent.com/7399594/381490657-40371845-a829-420b-a05e-10c07b921003.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyOTMyNzgsIm5iZiI6MTczMDI5Mjk3OCwicGF0aCI6Ii83Mzk5NTk0LzM4MTQ5MDY1Ny00MDM3MTg0NS1hODI5LTQyMGItYTA1ZS0xMGMwN2I5MjEwMDMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMzBUMTI1NjE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDg1ZTgyYWY2MTdlYTljMjdjMjgyYzk0NDg5MTBlMzRmYWFmNGY4OWQzZTRlNDU1MDM4NjRmNjVhNTA3N2I2ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.8LYAdLaDK9SQGfvxGmNPyP0k3XuNGwmy5Oe5gXYEUwM)

This is another "behavior", because it's linked to quests that have been updated = rewards have changed (either removed, or replaced by other items). Even in retail, you never got rewarded retroactively for "removed from game" quest rewards. It should be another issue ticket anyway.
