### ISSUE TITLE
[BUG] Warlock and DK pets do 25% less damage than expected

### ISSUE THREAD

**Issue by Tharre** [ClassicWoWCommunity/cata-classic-bugs#328]
#### 1.1. Description

Currently on beta, every point of Attack Power that the pet has (the pet, not the owner) appears to give 25% less DPS than the 1 DPS / 14 AP formula would suggest, that every historic source mentions and that seems to apply to everything else (including hunter pets).

  #### 1.2. How to Reproduce
  To reproduce, start with an non-orc character without any talents. Write down the amount of AP your pet has and it's damage range (more precisely via `/dump UnitDamage("pet")`) in the character menu pet tab. Then equip or unequip different pieces of gear or buff yourself and/or the pet with buffs (like horn of winter) and note how the AP and damage range changes.
  You'll end up with a table like this:
 |  AP  | Dmg Min | Dmg Max |
 | ---- | ------- | ------- |
 |  608 | 140.531 | 176.053 |
 |  918 | 175.960 | 211.482 |
 | 1227 | 211.388 | 246.910 |
 | 1695 | 264.759 | 300.282 |
 
 Taking any 2 points in this list, i.e. `(608, 140.531)` and `(918, 175.960)` we can see that we get less damage increase per AP point than we'd expect, `(918-608)/14 * 2 ~= 44.29` (2 because attack speed of 2.0) while `175.960 - 140.531 = 35.429`. And the difference seems to be 25%, `(918-608)/14*.125 * 2 = 35.429`.
 
 This is not just a UI bug either, as can be confirmed on dummies.
#### 2.1. Description
DK and Warlock pets should be getting 1 DPS every 14 AP like everything else (including hunter pets, they do work on beta).
  #### 2.2 Source Material
Every guide explaining attack power and pets.

**Comment by Speaker1264** [comment]
> (918-608)/14*.125 * 2 = 35.429

I just wanted to bump this and say that this formula here has an error.  I think you meant (918-608)/14/1.25 * 2 = 35.429, otherwise it doesn't make sense.

Also, doing the same math pet scaling in game I getting 1.05/1.25 scaling, versus your 1/1.25 scaling. Going from 1452 ap to 3194 ap I saw damage go from 254.97 min dmg to 464.01 min dmg, and 295.34 max dmg to 504.38 max dmg. That's a difference of 209.04 min and max dmg. However, doing the ap formula 3194 ap - 1452 ap = 1742 ap. 1742 ap / 14 = 124.43 dps. 124.43 dps * 2 = 248.86 dmg.  248.86 is what it the difference should've been, not 209.04.  If you take 248.86 * 1.05/1.25 you get 209.04.  So, the scaling is not off by 1.25.  It is off by 1.05/1.25.

**Comment by CharWS** [comment]
Fixed for warlock pets
NAB for death knight pets

**Comment by Tharre** [comment]
> Fixed for warlock pets

Not fixed for warlock pets, still the same scaling as in my original post on current live.

**Comment by powerlol** [comment]
Is it fixed on live now? Since he said it was fixed on NA down time - prolly wasn't updated on EU @Tharre

**Comment by Tharre** [comment]
@powerlol nope, still the same.

Here's a updated table from data that I just collected, for fel hunter on an orc warlock. The base damage has changed since my original post because of a different bug that has been fixed some time ago, but the scaling is still 25% worse than 14 AP/DPS. Note that since the data is from an orc, it contains the 5% extra damage from command:

AP | Dmg Min | Dmg Max
-- | -- | --
608 | 350.032 | 488.569
751 | 367.192 | 505.729
1718 | 483.352 | 621.889
1938 | 509.752 | 648.289

Taking any two points, i.e. `(751, 367.192)`, and `(1718 , 483.352)` still gives a difference of `483.352 - 367.192 = 116.16` instead of `(1718-751)/14 * 2 * 1.05 = 145.05` (times 1.05 because of the command racial).

`145.05 / 116.16 ~= 1.249` or about 25% worse

**Comment by JamminL** [comment]
Archiving old non-relevant issues in preparation for MOP. If I made a mistake please comment on it.
